services:
  backend:
    build:
      context: ./BackendDjango
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./BackendDjango/weather_app_backend:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./FrontendReact
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./FrontendReact/weather_app_frontend:/usr/src/app/weather_app_frontend
    environment:
      - NODE_ENV=production

